apiVersion: v1
kind: Service
metadata:
  name: cinellex-api-svc
  namespace: cinellex
spec:
  selector:
    app: cinellex-ai
    component: api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: cinellex-api-nodeport
  namespace: cinellex
spec:
  selector:
    app: cinellex-ai
    component: api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
  type: NodePort