apiVersion: v1
kind: ConfigMap
metadata:
  name: cinellex-config
  namespace: cinellex-staging
data:
  MLFLOW_TRACKING_URI: "file:///app/mlruns"
  API_URL: "http://cinellex-api-svc.cinellex.svc.cluster.local:8000"
