apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinellex-ai-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/warazkhan/CineLex-AI
    targetRevision: gitops        # watches gitops branch now
    path: k8s/staging             # staging manifests
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: cinellex-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
