apiVersion: v1
kind: Pod
metadata:
  name: seed-data
  namespace: cinellex-production
spec:
  restartPolicy: Never
  volumes:
    - name: data-vol
      persistentVolumeClaim:
        claimName: cinellex-data-pvc
  containers:
    - name: seed
      image: warazkhan/cinellex-ai:latest
      imagePullPolicy: IfNotPresent
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data-vol
          mountPath: /data
