name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest cinellex_rag/tests/ -v
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          warazkhan/cinellex-ai:latest
          warazkhan/cinellex-ai:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

  update-manifest:
    name: Update K8s Image Tag
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name != 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        ref: ${{ github.ref_name }}

    - name: Update image tag in k8s manifests
      run: |
        NEW_TAG="${{ github.sha }}"
        IMAGE="warazkhan/cinellex-ai"
        sed -i "s|image: ${IMAGE}:.*|image: ${IMAGE}:${NEW_TAG}|g" k8s/04-api-deployment.yaml
        sed -i "s|image: ${IMAGE}:.*|image: ${IMAGE}:${NEW_TAG}|g" k8s/06-streamlit-deployment.yaml

    - name: Commit and push updated manifests
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/04-api-deployment.yaml k8s/06-streamlit-deployment.yaml
        git diff --staged --quiet || git commit -m "ci: bump image tag to ${{ github.sha }}"
        git push origin ${{ github.ref_name }}